from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import BodyLabel, CompactDoubleSpinBox, RadioButton, SwitchButton, TitleLabel

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1223, 802)
        self.SwitchButton = SwitchButton(Form)
        self.SwitchButton.setGeometry(QtCore.QRect(450, 140, 91, 51))
        self.SwitchButton.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.SwitchButton.setObjectName("SwitchButton")
        self.CompactDoubleSpinBox = CompactDoubleSpinBox(Form)
        self.CompactDoubleSpinBox.setGeometry(QtCore.QRect(450, 220, 79, 51))
        self.CompactDoubleSpinBox.setMinimumSize(QtCore.QSize(79, 33))
        self.CompactDoubleSpinBox.setMaximumSize(QtCore.QSize(1000, 1000))
        self.CompactDoubleSpinBox.setMouseTracking(False)
        self.CompactDoubleSpinBox.setMinimum(18.0)
        self.CompactDoubleSpinBox.setMaximum(30.0)
        self.CompactDoubleSpinBox.setProperty("value", 25.0)
        self.CompactDoubleSpinBox.setObjectName("CompactDoubleSpinBox")
        self.TitleLabel = TitleLabel(Form)
        self.TitleLabel.setGeometry(QtCore.QRect(530, 50, 123, 37))
        self.TitleLabel.setObjectName("TitleLabel")
        self.BodyLabel = BodyLabel(Form)
        self.BodyLabel.setGeometry(QtCore.QRect(460, 110, 61, 21))
        self.BodyLabel.setObjectName("BodyLabel")
        self.BodyLabel_2 = BodyLabel(Form)
        self.BodyLabel_2.setGeometry(QtCore.QRect(460, 190, 63, 19))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.RadioButton = RadioButton(Form)
        self.RadioButton.setGeometry(QtCore.QRect(670, 230, 51, 24))
        self.RadioButton.setObjectName("RadioButton")
        self.BodyLabel_3 = BodyLabel(Form)
        self.BodyLabel_3.setGeometry(QtCore.QRect(650, 190, 63, 19))
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.RadioButton_2 = RadioButton(Form)
        self.RadioButton_2.setGeometry(QtCore.QRect(730, 230, 51, 24))
        self.RadioButton_2.setObjectName("RadioButton_2")
        self.RadioButton_3 = RadioButton(Form)
        self.RadioButton_3.setGeometry(QtCore.QRect(600, 230, 51, 24))
        self.RadioButton_3.setObjectName("RadioButton_3")
        self.BodyLabel_4 = BodyLabel(Form)
        self.BodyLabel_4.setGeometry(QtCore.QRect(660, 110, 63, 19))
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.BodyLabel_5 = BodyLabel(Form)
        self.BodyLabel_5.setGeometry(QtCore.QRect(660, 140, 63, 19))
        self.BodyLabel_5.setObjectName("BodyLabel_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.TitleLabel.setText(_translate("Form", "空调面板"))
        self.BodyLabel.setText(_translate("Form", "空调开关"))
        self.BodyLabel_2.setText(_translate("Form", "设定温度"))
        self.RadioButton.setText(_translate("Form", "中"))
        self.BodyLabel_3.setText(_translate("Form", "设定风速"))
        self.RadioButton_2.setText(_translate("Form", "高"))
        self.RadioButton_3.setText(_translate("Form", "低"))
        self.BodyLabel_4.setText(_translate("Form", "房间号"))
        self.BodyLabel_5.setText(_translate("Form", "2-233"))

